version: "3"
services:
  python:
     image: "federatedai/python:1.4.4-release"
     ports:
            - "9380:9380"
            - "9360:9360"
     volumes:
            - "./fate/log:/fate/logs"
            - "/etc/localtime:/etc/localtime"
     container_name: fate_python
  fateboard:
     image: "federatedai/fateboard:1.4.4-release"
     links:
            - python
     ports:
            - "8080:8080"
     depends_on:
            - python
     volumes:
            - "./fate/log:/data/projects/fate/python/logs"
            - "/etc/localtime:/etc/localtime"
     container_name: fate_fateboard
